/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BespokeServicesRouteImport } from './routes/bespoke-services'
import { Route as CommitmentRouteImport } from './routes/commitment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiamodsRouteImport } from './routes/diamods'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as NewsAndEventsRouteImport } from './routes/news-and-events'
import { Route as ProductsRouteImport } from './routes/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeServicesRoute = BespokeServicesRouteImport.update({
  id: '/bespoke-services',
  path: '/bespoke-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentRoute = CommitmentRouteImport.update({
  id: '/commitment',
  path: '/commitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamodsRoute = DiamodsRouteImport.update({
  id: '/diamods',
  path: '/diamods',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAndEventsRoute = NewsAndEventsRouteImport.update({
  id: '/news-and-events',
  path: '/news-and-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bespoke-services': typeof BespokeServicesRoute
  '/commitment': typeof CommitmentRoute
  '/contact': typeof ContactRoute
  '/diamods': typeof DiamodsRoute
  '/manufacturing': typeof ManufacturingRoute
  '/news-and-events': typeof NewsAndEventsRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bespoke-services': typeof BespokeServicesRoute
  '/commitment': typeof CommitmentRoute
  '/contact': typeof ContactRoute
  '/diamods': typeof DiamodsRoute
  '/manufacturing': typeof ManufacturingRoute
  '/news-and-events': typeof NewsAndEventsRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bespoke-services': typeof BespokeServicesRoute
  '/commitment': typeof CommitmentRoute
  '/contact': typeof ContactRoute
  '/diamods': typeof DiamodsRoute
  '/manufacturing': typeof ManufacturingRoute
  '/news-and-events': typeof NewsAndEventsRoute
  '/products': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bespoke-services'
    | '/commitment'
    | '/contact'
    | '/diamods'
    | '/manufacturing'
    | '/news-and-events'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bespoke-services'
    | '/commitment'
    | '/contact'
    | '/diamods'
    | '/manufacturing'
    | '/news-and-events'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bespoke-services'
    | '/commitment'
    | '/contact'
    | '/diamods'
    | '/manufacturing'
    | '/news-and-events'
    | '/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BespokeServicesRoute: typeof BespokeServicesRoute
  CommitmentRoute: typeof CommitmentRoute
  ContactRoute: typeof ContactRoute
  DiamodsRoute: typeof DiamodsRoute
  ManufacturingRoute: typeof ManufacturingRoute
  NewsAndEventsRoute: typeof NewsAndEventsRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke-services': {
      id: '/bespoke-services'
      path: '/bespoke-services'
      fullPath: '/bespoke-services'
      preLoaderRoute: typeof BespokeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitment': {
      id: '/commitment'
      path: '/commitment'
      fullPath: '/commitment'
      preLoaderRoute: typeof CommitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamods': {
      id: '/diamods'
      path: '/diamods'
      fullPath: '/diamods'
      preLoaderRoute: typeof DiamodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-and-events': {
      id: '/news-and-events'
      path: '/news-and-events'
      fullPath: '/news-and-events'
      preLoaderRoute: typeof NewsAndEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BespokeServicesRoute: BespokeServicesRoute,
  CommitmentRoute: CommitmentRoute,
  ContactRoute: ContactRoute,
  DiamodsRoute: DiamodsRoute,
  ManufacturingRoute: ManufacturingRoute,
  NewsAndEventsRoute: NewsAndEventsRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
